---
extraMounts:
    - device: proc
      mountPoint: /proc
    - device: sys
      mountPoint: /sys
    - device: dev
      mountPoint: /dev
    - device: tmpfs
      mountPoint: /tmp
      options: [ mode=1777 ]
