---
defaultGroups:
    - video
    - audio
    - lp
    - scanner
    - wheel
    - network
    - video
autologinGroup:  autologin
doAllowDefaultPasswordPolicy: false
sudoersGroup:    wheel
setRootPassword: true
doNotFormatHome: true
