---
modules-search: [ "/usr/lib/calamares/modules" ]

instances:
- id:       shellprocess
  module:   shellprocess
  config:   shellprocess.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - networkcfg
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkmanager
  - hwclock
  - services-systemd
  - bootloader
  - shellprocess
  - umount
- show:
  - finished

branding: kyberos
prompt-install: true
dont-chroot: false
