---
modules-search: [ local ]

instances:
- id:       side_selection
  module:   shellprocess
  config:   side_selection.conf

- id:       knowledge_bundles
  module:   shellprocess
  config:   knowledge_bundles.conf

- id:       bleed_crystal
  module:   shellprocess
  config:   bleed_crystal.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - side_selection
  - knowledge_bundles
  - bleed_crystal
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - networkcfg
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkmanager
  - hwclock
  - services-systemd
  - bootloader
  - shellprocess
  - umount
- show:
  - finished

branding: kyberos
prompt-install: true
dont-chroot: false
